#!/usr/bin/env bash

set -e

export LC_ALL=C

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR="$SCRIPT_DIR/../.."

TMP_DIR=$(mktemp -d)

cd "$TMP_DIR"

######################

function fail() {
  echo
  echo "Arguments: $(printf "'%s' " "$@")"
  exit 1
}

function test_solution() {
  diff --color=always -U 1000 \
    <(echo "$EXPECTED") \
    <(bash "$ROOT_DIR/solution/task3.sh" "$@") \
    || fail "$@"
}


echo "Test case #1"

EXPECTED='13 октября 2023 года, Пятница'
test_solution '2023-10-13'


echo "Test case #2"

EXPECTED='1 января 1970 года, Четверг'
test_solution '@0'


echo "Test case #3"

EXPECTED='29 февраля 2024 года, Четверг'
test_solution '2024-02-29'
